const mongoose=require("mongoose");
const courseSchema=new mongoose.Schema({
    courseName:{
        type:String,
    },
    courseDescription:{
        type:String,
    },
    instructor:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true,
    },
    whatYouwillLearn:{
        type:String,
    },
    courseContent:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Section",
    },
    ratingAndReviews:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"RatingAndReviews",
    },
    price:{
        type:Number,
    },
    thumbnail:{
        type:String,
    },
    tag:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Tags",
    },
    category:{
        type:mongoose.Schema.Types.ObjectId,
        //require:true,
        ref:"categories",
    },
    studentEnrolled:{
        type:String,
    },
    instructions:{
         type:[String],
    },
    status:{
      type:String,
      enum:["Draft","Published"],
    },
});
//exports the courses model
module.exports=mongoose.model("Course",courseSchema)